amazon-braket/Braket.jl

- src/Braket.jl
- src/device.jl
- test/ahs.jl
`AwsDevice` functor didn't accept `AnalogHamiltonianSimulation`s. This fixes this and adds a test.
Added mock test.
> Fix AwsDevice to run on Aquila

- examples/ahs_nb.jl
- examples/ahs_rabi.jl
1. Small change for ahs_rabi.jl including changing  the title and some other small places
2. Big changes for ahs_nb.jl including add texts and restructure the notebooks
> modify two nbs

- examples/ahs_nb.jl
- examples/ahs_rabi.jl
Cleanup now that packages are registered, and added another notebook about measuring the Rabi frequency.
> Add Rabi frequency notebook and update others

- CHANGELOG.md
- Project.toml
- PyBraket/CHANGELOG.md
- PyBraket/Project.toml
- PyBraket/test/Project.toml
> Version bump to 0.2.0 for both Braket and PyBraket

- examples/adjoint_gradient.jl
- examples/qft.jl
N/A
Improved text in QFT notebook.
Added missing final line to AG notebook.
Added warning and empty block to AG notebook about AWS credentials.
Run locally in Pluto.
> change: Add more text to QFT notebook and final line and warning about creds to AG notebook.

- src/jobs.jl
N/A
Existing code didn't gracefully deal with the fact that not all metrics keys will have the same timestamps.
Tested with a job emitting multiple metrics at different times.
> fix: Fix handling of metrics

- examples/vqe_chemistry.jl
N/A
Add a Pluto notebook explaining quantum chemistry basics using VQE.
Ran notebook locally.
> Add example notebook for basic VQE chemistry example

- Project.toml
N/A
Bump to new AWSS3.jl version
Unit and integ tests passed locally
> Bump AWSS3 version

- src/Braket.jl
- test/free_parameter.jl
> Few missing methods for FreeParameter

- Project.toml
- PyBraket/Project.toml
> Bump to 0.4.1

- examples/tetris_vqe.jl
N/A
Added an example notebook showing how to use TETRIS-ADAPT-VQE with PennyLane and Braket.jl
Ran locally.
> change: add TETRIS-ADAPT-VQE notebook

- Project.toml
- PyBraket/Project.toml
N/A
Bump to v0.5.0
Previously passed CI, no other changes besides bump.
> change: version bump

- src/Braket.jl
- src/circuit.jl
- src/compiler_directive.jl
- src/gates.jl
- src/moments.jl
- src/noises.jl
- src/observables.jl
- src/results.jl
- test/circuits.jl
#14 
Add pure Julia logic for pretty printing circuits. Mostly replicates Python functionality. Further improvements could be made but this works as a start. Example:
```julia
using Braket
a = FreeParameter("α")
c = Circuit([(H, collect(0:10)), (CNot, 0, 1), (CNot, 1, 3), (H, 2), (H, 2), (Rx, 0, a), (Expectation, Braket.Observables.TensorProduct(["x", "y"]), [0, 2]), (Variance, Braket.Observables.TensorProduct(["z", "x"]), [2, 1]), (Amplitude, "1111"), (Probability,)])
d = Circuit([(H, 0), (X, 1)])
c = Braket.add_verbatim_box!(c, d)
```
yields:
```
T   : |0|1|  2   |      3      |4|     5     |                 Result Types                 |
q0  : -H-C--Rx(α)-StartVerbatim-H-EndVerbatim-Expectation(X @ Y)-----------------Probability-
| …
```
> feature: add pure Julia circuit pretty-printing

- README.md
- src/qubit_set.jl
- src/task_batch.jl
- test/circuits.jl
- test/gates.jl
- test/observables.jl
- test/qubit_set.jl
- test/runtests.jl
- test/task.jl
- test/task_batch.jl
- test/translation.jl
N/A
Discovered a bug related to passing a vector of input dictionaries when launching a batch of tasks. Fixed that and added a variety of tests.
Tests pass locally.
> fix: fix inputs bug in launch_batch and add more tests

- src/circuit.jl
- src/compiler_directive.jl
- test/circuits.jl
- test/compiler_directives.jl
- test/gate_model_task_result.jl
N/A
Add more tests and sort the moments when applying noise.
Tests pass locally.
> change: More tests and sort moments when applying noise

- Project.toml
- PyBraket/Project.toml
*Description of changes:* Bump patch version with more tests and small fixes.
*Testing done:* Tests passed locally.
> change: bump to 0.5.1

- Project.toml
- PyBraket/Project.toml
Bump `Braket.jl` and `PyBraket.jl` to `0.6.0`. Bump `PythonCall` and `Compat` dep versions.
Tests passed locally.
> change: Bump deps and versions

- .github/workflows/CI.yml
- Project.toml
- PyBraket/Project.toml
*Issue #, if available:* N/A, addresses issue caused by HTTP.jl 1.8.0
*Description of changes:* Bump dep versions
*Testing done:* Unit tests passed locally
> change: Bump packages

- Project.toml
- PyBraket/Project.toml
*Description of changes:* Bumped both Braket and PyBraket to 0.8, upgraded PyBraket deps CondaPkg and PythonCall
*Testing done:* Unit tests passed locally
> change: bump version to 0.8.0, upgrade PyBraket deps

- README.md
*Description of changes:* Looks like Codecov wants a new URL for our coverage badge
*Testing done:* N/A
> fix: New URL for coverage badge

- Project.toml
- PyBraket/Project.toml
- src/local_simulator.jl
*Description of changes:* Fixed property lookup for batched tasks
*Testing done:* Unit tests passed locally, `BraketSimulator.jl` unstuck
> fix: batch task result field

- src/device.jl
- test/device.jl
- test/integ_tests/cost_tracking.jl
- test/integ_tests/device_creation.jl
- test/task.jl
- test/task_batch.jl
> change: Replace Aspen-M-3 with Ankaa-2
